language: node_js
node_js: node
cache:
  directories:
  - /home/travis/.elm
  - node_modules
  - elm-stuff
git:
  depth: 150
branches:
  only:
  - master
install:
- npm install -g elm@0.19.0 uglify-js@3.4.7
- curl -OL http://dl.itch.ovh/butler/linux-amd64/head/butler
- chmod +x butler
env:
  global:
    secure: NUKnepDTgmNpEV6aJFCre+lBb1QPbYz3US0GyRcLWQjls9uV2OJuMDAMKKxYJ9Zb5o2v3rrt3WmgdmesSCMjTdN73gXY4ypnD5bbXdl1zIZrtuCj1psBrfc6nfv98CjGAW8ejsK8722L5JQHFgEk65x9Vs2bam1RroDDYtPQTrVOBRk/YJBm/84QfBPzjUoPwa8lZzzBHJr7wP3EqnWT4m14WzBditcBp2An+rReiVUKAxc7XckOEV6MRsk6xGLfhGMnjQhvn7OwajSvfrXfZovPkwf6AGS6lCKZwr3KARCiqStS4+fgjrP8f8EVGwzyPz9vB/XVH6J1Q+F1CgvXypqTiJpmy3fZtdC95DeYgrlisbKBDRRiZ2yiEqiOWOvBvmFomeVnJ/ljq+diEHmtbRX4ZhsKSP7R4VCzXyJvxlaksXB178Ebc4Yx9bJZnhqJsIfS6QqH4UsPmeQpNAzzlbn5A4xcWqPATnhf91WFxrE5Ipxlxk48x/RO1DsszFGVsubSTLZN8/yp0KPH6nemrc2XduOLEYgug+cfaqDGr+SERA1m2TuBsYOlBaDSAvxtAdYhQ+3XHtnvvLoKdr77GwteZuzgMxR75DwcH47CNufWRPCF9EwRnFc2KxitwSTDHcoJG309jCA8ch988R1WP8PUVw0bJzpxsigi3AADlAg=
script:
- ./scripts/deploy.sh
notifications:
  email:
    recipients:
    - unsoundscapes@gmail.com
